### ISSUE TITLE
React Style To Css ???

### ISSUE THREAD

**Issue by xyzdata** [staxmanade/CssToReact#6]
# Css To React

> CssToReact

http://staxmanade.com/CssToReact/

## how to fixed this bug ???

```css
.sidebar-btn::after {
    color: #0f0;
    background: #000;
    width: 20px;
    margin: auto 5px;
    height: 50px;
    content: 'B';
    position: absolute;
    left: 240px;
    top: 35%;
    cursor: pointer;
}
```

```jsx
{
  "sidebar_btn__after": {
    "color": "#0f0",
    "background": "#000",
    "width": "20px",
    "margin": "auto 5px",
    "height": "50px",
    "content": "'B'",
    "position": "absolute",
    "left": "240px",
    "top": "35%",
    "cursor": "pointer"
  }
}
```

# React To Css

> ???

http://reactcss.com/
